// 全域變數 (不要用 const，避免重新載入時出錯)
//{ type: 'noun', deutsch: '', chinese: '', gender: '', plural: '', Pl: '', countable: false/true, lesson: '', hint: '' },
// 特殊字符 Ä ä Ö ö Ü ü ß

window.vocabNouns = [
// 國家 語言 城市(名詞)
    { type: 'country', deutsch: 'Deutschland', chinese: '德國', countable: false, lesson: 'lesson 1' },
    { type: 'country', deutsch: 'Deutsch', chinese: '德語', countable: false, lesson: 'lesson 1' },
    { type: 'country', deutsch: 'Spanien', chinese: '西班牙', countable: false, lesson: 'lesson 1' },
    { type: 'country', deutsch: 'Spanisch', chinese: '西班牙語', countable: false, lesson: 'lesson 1' },
    { type: 'country', deutsch: 'Japan', chinese: '日本', countable: false, lesson: 'lesson 1' },
    { type: 'country', deutsch: 'Japanisch', chinese: '日語', countable: false, lesson: 'lesson 1' },
    { type: 'country', deutsch: 'Indonesien', chinese: '印尼', countable: false, lesson: 'lesson 1' },
    { type: 'country', deutsch: 'Indonesisch', chinese: '印尼語', countable: false, lesson: 'lesson 1' },
    { type: 'country', deutsch: 'England', chinese: '英國', countable: false, lesson: 'lesson 1' },
    { type: 'country', deutsch: 'Englisch', chinese: '英語', countable: false, lesson: 'lesson 1' },
    { type: 'country', deutsch: 'die U.S.A.', chinese: '美國', countable: true, plural:true, lesson: 'lesson 1' },
    { type: 'country', deutsch: 'die Niederlande', chinese: '荷蘭', countable: true, plural:true, lesson: 'lesson 1' },
    { type: 'country', deutsch: 'Niederländisch', chinese: '荷蘭語', countable: false, lesson: 'lesson 1' },
    { type: 'country', deutsch: 'China', chinese: '中國', countable: false, lesson: 'lesson 1' },
    { type: 'country', deutsch: 'Chinesisch', chinese: '中文', countable: false, lesson: 'lesson 1' },
    { type: 'country', deutsch: 'Kamerun', chinese: '喀麥隆', countable: false, lesson: 'lesson 1' },
    { type: 'country', deutsch: 'Kamtok', chinese: '皮欽語', countable: false, lesson: 'lesson 1' },
    { type: 'country', deutsch: 'Vietnam', chinese: '越南', countable: false, lesson: 'lesson 1' },
    { type: 'country', deutsch: 'Vietnamesisch', chinese: '越南語', countable: false, lesson: 'lesson 1' },
    { type: 'country', deutsch: 'Russland', chinese: '俄羅斯', countable: false, lesson: 'lesson 1' },
    { type: 'country', deutsch: 'Russisch', chinese: '俄語', countable: false, lesson: 'lesson 1' },
    { type: 'country', deutsch: 'Italien', chinese: '義大利', countable: false, lesson: 'lesson 1' },
    { type: 'country', deutsch: 'Italienisch', chinese: '義大利語', countable: false, lesson: 'lesson 1' },
    { type: 'country', deutsch: 'Arabien', chinese: '阿拉伯', countable: false, lesson: 'lesson 1' },
    { type: 'country', deutsch: 'Arabisch', chinese: '阿拉伯語', countable: false, lesson: 'lesson 1' },
    { type: 'country', deutsch: 'Norwegen', chinese: '挪威', countable: false, lesson: 'lesson 1' },
    { type: 'country', deutsch: 'Norwegisch', chinese: '挪威語', countable: false, lesson: 'lesson 1' },
    { type: 'country', deutsch: 'Tschechien', chinese: '捷克', countable: false, lesson: 'lesson 1' },
    { type: 'country', deutsch: 'Tschechisch', chinese: '捷克語', countable: false, lesson: 'lesson 1' },
    { type: 'country', deutsch: 'Polen', chinese: '波蘭', countable: false, lesson: 'lesson 1' },
    { type: 'country', deutsch: 'Polnisch', chinese: '波蘭語', countable: false, lesson: 'lesson 1' },
    { type: 'country', deutsch: 'Dänemark', chinese: '丹麥', countable: false, lesson: 'lesson 1' },
    { type: 'country', deutsch: 'Dänisch', chinese: '丹麥語', countable: false, lesson: 'lesson 1' },
    { type: 'country', deutsch: 'die Schweiz', chinese: '瑞士', countable: true, plural:false, lesson: 'lesson 1' },
    { type: 'country', deutsch: 'Frankreich', chinese: '法國', countable: false, lesson: 'lesson 1' },
    { type: 'country', deutsch: 'Französisch', chinese: '法語', countable: false, lesson: 'lesson 1' },
    { type: 'country', deutsch: 'der Iran', chinese: '伊朗', countable: false, lesson: 'lesson 1' },
    { type: 'country', deutsch: 'Farsi', chinese: '波斯語', countable: false, lesson: 'lesson 1' },
    { type: 'country', deutsch: 'die Türkei', chinese: '土耳其', countable: false, lesson: 'lesson 1' },
    { type: 'country', deutsch: 'Türkisch', chinese: '土耳其語', countable: false, lesson: 'lesson 1' },
    { type: 'country', deutsch: 'Portugal', chinese: '葡萄牙', countable: false, lesson: 'lesson 1' },
    { type: 'country', deutsch: 'Portugiesisch', chinese: '葡萄牙語', countable: false, lesson: 'lesson 1' },
    { type: 'country', deutsch: 'Brasilien', chinese: '巴西', countable: false, lesson: 'lesson 1' },
    { type: 'country', deutsch: 'Thailand', chinese: '泰國', countable: false, lesson: 'lesson 1' },
    { type: 'country', deutsch: 'Thai', chinese: '泰語', countable: false, lesson: 'lesson 1' },
    { type: 'country', deutsch: 'Neuseeland', chinese: '紐西蘭', countable: false, lesson: 'lesson 1' },
    { type: 'country', deutsch: 'Bulgarien', chinese: '保加利亞', countable: false, lesson: 'lesson 1' },
    { type: 'country', deutsch: 'Österreich', chinese: '奧地利', countable: false, lesson: 'lesson 1' },
    { type: 'country', deutsch: 'Luxemburg', chinese: '盧森堡', countable: false, lesson: 'lesson 1' },
    { type: 'country', deutsch: 'Schweden', chinese: '瑞典', countable: false, lesson: 'lesson 1' },
    { type: 'country', deutsch: 'Schwedisch', chinese: '瑞典語', countable: false, lesson: 'lesson 1' },
    { type: 'country', deutsch: 'Finnland', chinese: '芬蘭', countable: false, lesson: 'lesson 1' },
    { type: 'country', deutsch: 'Finnisch', chinese: '芬蘭語', countable: false, lesson: 'lesson 1' },
    { type: 'country', deutsch: 'Belgien', chinese: '比利時', countable: false, lesson: 'lesson 1' },
    { type: 'country', deutsch: 'Berlin', chinese: '柏林', countable: false, lesson: 'lesson 1' },
    { type: 'country', deutsch: 'Bern', chinese: '伯恩', countable: false, lesson: 'lesson 1' },
    { type: 'country', deutsch: 'Lugano', chinese: '盧加諾', countable: false, lesson: 'lesson 1' },
    { type: 'country', deutsch: 'Zürich', chinese: '蘇黎士', countable: false, lesson: 'lesson 1' },
    { type: 'country', deutsch: 'Genf', chinese: '日內瓦', countable: false, lesson: 'lesson 1' },
    { type: 'country', deutsch: 'Isfahan', chinese: '伊斯法罕', countable: false, lesson: 'lesson 1' },
    { type: 'country', deutsch: 'Leipzig', chinese: '萊比錫', countable: false, lesson: 'lesson 1' },
    { type: 'country', deutsch: 'Auckland', chinese: '奧克蘭', countable: false, lesson: 'lesson 1' },
    { type: 'country', deutsch: 'Syrien', chinese: '敘利亞', countable: false, lesson: 'lesson 2' },
    { type: 'country', deutsch: 'Argentinien', chinese: '阿根廷', countable: false, lesson: 'lesson 2' },
    { type: 'country', deutsch: 'Dortmund', chinese: '多特蒙德', countable: false, lesson: 'lesson 2' },
    { type: 'country', deutsch: 'Torrent', chinese: '多倫特', countable: false, lesson: 'lesson 2' },
    { type: 'country', deutsch: 'Stuttgart', chinese: '斯圖加特', countable: false, lesson: 'lesson 2' },
    { type: 'country', deutsch: 'Müsingen', chinese: '明辛恩', countable: false, lesson: 'lesson 2' },
    

//其餘名詞
    //lesson 0
    { type: 'noun', deutsch: 'Kursraum', chinese: '教室', gender: 'der', plural: 'Kursräume', Pl: '-:e', countable: true, lesson: 'lesson 0' },
    { type: 'noun', deutsch: 'Tisch', chinese: '桌', gender: 'der', plural: 'Tische', Pl: '-e', countable: true, lesson: 'lesson 0' },
    { type: 'noun', deutsch: 'Stuhl', chinese: '椅', gender: 'der', plural: 'Stühle', Pl: '-:e', countable: true, lesson: 'lesson 0' },
    { type: 'noun', deutsch: 'Kuli', chinese: '原子筆', gender: 'der', plural: 'Kulis', Pl: '-s', countable: true, lesson: 'lesson 0' },
    { type: 'noun', deutsch: 'Stift', chinese: '筆', gender: 'der', plural: 'Stifte', Pl: '-e', countable: true, lesson: 'lesson 0' },
    { type: 'noun', deutsch: 'Bleistift', chinese: '鉛筆', gender: 'der', plural: 'Bleistifte', Pl: '-e', countable: true, lesson: 'lesson 0' },
    { type: 'noun', deutsch: 'Gegenstand', chinese: '東西 物件', gender: 'der', plural: 'Gegenstände', Pl: '-:e', countable: true, lesson: 'lesson 0' },
    { type: 'noun', deutsch: 'Text', chinese: '文章', gender: 'der', plural: 'Texte', Pl: '-e', countable: true, lesson: 'lesson 0' },
    { type: 'noun', deutsch: 'Marker', chinese: '馬克筆', gender: 'der', plural: 'Marker', Pl: '-', countable: true, lesson: 'lesson 0', hint: 'M'},
    { type: 'noun', deutsch: 'Textmarker', chinese: '馬克筆', gender: 'der', plural: 'Textmarker', Pl: '-', countable: true, lesson: 'lesson 0', hint: 'T' },
    { type: 'noun', deutsch: 'Laptop', chinese: '筆電', gender: 'der', plural: 'Laptops', Pl: '-s', countable: true, lesson: 'lesson 0' },
    { type: 'noun', deutsch: 'Kaffee', chinese: '咖啡', gender: 'der', plural: 'Kaffees', Pl: '-s', countable: true, lesson: 'lesson 0' },
    { type: 'noun', deutsch: 'Tee', chinese: '茶', gender: 'der', plural: 'Tees', Pl: '-s', countable: true, lesson: 'lesson 0' },
    { type: 'noun', deutsch: 'Radiergummi', chinese: '橡皮擦', gender: 'der', plural: 'Radiergummis', Pl: '-s', countable: true, lesson: 'lesson 0' },
    { type: 'noun', deutsch: 'Buch', chinese: '書', gender: 'das', plural: 'Bücher', Pl: '-:er', countable: true, lesson: 'lesson 0' },
    { type: 'noun', deutsch: 'Heft', chinese: '筆記本', gender: 'das', plural: 'Hefte', Pl: '-e', countable: true, lesson: 'lesson 0' },
    { type: 'noun', deutsch: 'Wort', chinese: '字', gender: 'das', plural: 'Wörter', Pl: '-:er', countable: true, lesson: 'lesson 0' },
    { type: 'noun', deutsch: 'Handy', chinese: '手機', gender: 'das', plural: 'Handys', Pl: '-s', countable: true, lesson: 'lesson 0' },
    { type: 'noun', deutsch: 'Plakat', chinese: '佈告欄 看板', gender: 'das', plural: 'Plakate', Pl: '-e', countable: true, lesson: 'lesson 0' },
    { type: 'noun', deutsch: 'Brot', chinese: '麵包', gender: 'das', plural: 'Brote', Pl: '-e', countable: true, lesson: 'lesson 0' },
    { type: 'noun', deutsch: 'Brötchen', chinese: '小麵包', gender: 'das', plural: 'Brötchen', Pl: '-', countable: true, lesson: 'lesson 0' },
    { type: 'noun', deutsch: 'Tafel', chinese: '黑板', gender: 'die', plural: 'Tafeln', Pl: '-n', countable: true, lesson: 'lesson 0' },
    { type: 'noun', deutsch: 'Tür', chinese: '門', gender: 'die', plural: 'Türen', Pl: '-en', countable: true, lesson: 'lesson 0' },
    { type: 'noun', deutsch: 'Uhr', chinese: '鐘錶', gender: 'die', plural: 'Uhren', Pl: '-en', countable: true, lesson: 'lesson 0' },
    { type: 'noun', deutsch: 'Tasche', chinese: '提袋 包包', gender: 'die', plural: 'Taschen', Pl: '-n', countable: true, lesson: 'lesson 0' },
    { type: 'noun', deutsch: 'Pause', chinese: '休息', gender: 'die', plural: 'Pausen', Pl: '-n', countable: true, lesson: 'lesson 0' },

    //lesson 1
    { type: 'noun', deutsch: 'Name', chinese: '姓名', gender: 'der', plural: 'Namen', Pl: '-n', countable: true, lesson: 'lesson 1' },
    { type: 'noun', deutsch: 'Vorname', chinese: '名(字)', gender: 'der', plural: 'Vornamen', Pl: '-n', countable: true, lesson: 'lesson 1' },
    { type: 'noun', deutsch: 'Nachname', chinese: '姓(氏)', gender: 'der', plural: 'Nachnamen', Pl: '-n', countable: true, lesson: 'lesson 1', hint: 'N' },
    { type: 'noun', deutsch: 'Familie', chinese: '家庭 家人', gender: 'die', plural: 'Familien', Pl: '-n', countable: true, lesson: 'lesson 1' },
    { type: 'noun', deutsch: 'Familienname', chinese: '姓(氏)', gender: 'der', plural: 'Familiennamen', Pl: '-n', countable: true, lesson: 'lesson 1', hint: 'F' },
    { type: 'noun', deutsch: 'Land', chinese: '國家', gender: 'das', plural: 'Länder', Pl: '-:er', countable: true, lesson: 'lesson 1' },
    { type: 'noun', deutsch: 'Nachbar', chinese: '鄰居', gender: 'der', plural: 'Nachbarn', Pl: '-n', countable: true, lesson: 'lesson 1' },
    { type: 'noun', deutsch: 'Nachbarland', chinese: '鄰國', gender: 'das', plural: 'Nachbarländer', Pl: '-:er', countable: true, lesson: 'lesson 1' },
    { type: 'noun', deutsch: 'Sprache', chinese: '語言', gender: 'die', plural: 'Sprachen', Pl: '-n', countable: true, lesson: 'lesson 1' },
    { type: 'noun', deutsch: 'Mutter', chinese: '母親', gender: 'die', plural: 'Mütter', Pl: '-:', countable: true, lesson: 'lesson 1' },
    { type: 'noun', deutsch: 'Muttersprache', chinese: '母語', gender: 'die', plural: 'Muttersprachen', Pl: '-n', countable: true, lesson: 'lesson 1' },
    { type: 'noun', deutsch: 'Ländername', chinese: '國名', gender: 'der', plural: 'Ländernamen', Pl: '-n', countable: true, lesson: 'lesson 1' },
    { type: 'noun', deutsch: 'Person', chinese: '人', gender: 'die', plural: 'Personen', Pl: '-en', countable: true, lesson: 'lesson 1' },
    { type: 'noun', deutsch: 'Tag', chinese: '天', gender: 'der', plural: 'Tage', Pl: '-e', countable: true, lesson: 'lesson 1' },
    { type: 'noun', deutsch: 'Sommer', chinese: '夏天', gender: 'der', countable: false, lesson: 'lesson 1' },
    { type: 'noun', deutsch: 'Kurs', chinese: '課程', gender: 'der', plural: 'Kurse', Pl: '-e', countable: true, lesson: 'lesson 1' },
    { type: 'noun', deutsch: 'Sommerkurs', chinese: '夏季語言班', gender: 'der', plural: 'Sommerkurse', Pl: '-e', countable: true, lesson: 'lesson 1' },
    { type: 'noun', deutsch: 'Stadt', chinese: '城市', gender: 'die', plural: 'Städte', Pl: '-:e', countable: true, lesson: 'lesson 1' },
    { type: 'noun', deutsch: 'Satz', chinese: '句子 (定理/規則/沉澱物)', gender: 'der', plural: 'Sätze', Pl: '-:e', countable: true, lesson: 'lesson 1' },
    { type: 'noun', deutsch: 'Frage', chinese: '疑問', gender: 'die', plural: 'Fragen', Pl: '-n', countable: true, lesson: 'lesson 1' },
    { type: 'noun', deutsch: 'Antwort', chinese: '回答', gender: 'die', plural: 'Antworten', Pl: '-en', countable: true, lesson: 'lesson 1' },
    { type: 'noun', deutsch: 'Satzfrage', chinese: '將直述句變成的問句', gender: 'die', plural: 'Satzfragen', Pl: '-n', countable: true, lesson: 'lesson 1' },
    { type: 'noun', deutsch: 'W-frage', chinese: '以疑問詞造的問句', gender: 'die', plural: 'W-fragen', Pl: '-n', countable: true, lesson: 'lesson 1' },
    { type: 'noun', deutsch: 'Wohnort', chinese: '住處', gender: 'der', plural: 'Wohnorte', Pl: '-e', countable: true, lesson: 'lesson 1' },

    //lesson 2
    { type: 'noun', deutsch: 'Zusteller', chinese: '郵差 快遞', gender: 'der', plural: 'Zusteller', Pl: '-', countable: true, lesson: 'lesson 2'},
    { type: 'noun', deutsch: 'Ahnung', chinese: '概念 印像', gender: 'die', plural: 'Ahnungen', Pl: '-en', countable: true, lesson: 'lesson 2'},
    { type: 'noun', deutsch: 'Entschuldigung', chinese: '對不起', gender: 'die', plural: 'Entschuldigungen', Pl: '-en', countable: true, lesson: 'lesson 2'},
    { type: 'noun', deutsch: 'Vorsicht', chinese: '小心 謹慎', gender: 'die', plural: '', Pl: '', countable: false, lesson: 'lesson 2'},
    { type: 'noun', deutsch: 'Klingel', chinese: '電鈴', gender: 'die', plural: 'Klingeln', Pl: '-n', countable: true, lesson: 'lesson 2'},
    { type: 'noun', deutsch: 'Adresse', chinese: '地址', gender: 'die', plural: 'Adressen', Pl: '-n', countable: true, lesson: 'lesson 2'},
    { type: 'noun', deutsch: 'Brief', chinese: '信', gender: 'der', plural: 'Briefe', Pl: '-e', countable: true, lesson: 'lesson 2'},
    { type: 'noun', deutsch: 'Paket', chinese: '包裹', gender: 'das', plural: 'Pakete', Pl: '-e', countable: true, lesson: 'lesson 2'},
    { type: 'noun', deutsch: 'Arbeit', chinese: '工作 作品', gender: 'die', plural: 'Arbeiten', Pl: '-en', countable: true, lesson: 'lesson 2'},
    { type: 'noun', deutsch: 'Zeit', chinese: '時間', gender: 'die', plural: '', Pl: '', countable: false, lesson: 'lesson 2'},
    { type: 'noun', deutsch: 'Hund', chinese: '狗', gender: 'der', plural: 'Hunde', Pl: '-e', countable: true, lesson: 'lesson 2'},
    { type: 'noun', deutsch: 'Tempo', chinese: '速度 速率', gender: 'das', plural: 'Tempi', Pl: '', countable: true, lesson: 'lesson 2'},
    { type: 'noun', deutsch: 'Stress', chinese: '壓力', gender: 'der', plural: '', Pl: '', countable: false, lesson: 'lesson 2'},
    { type: 'noun', deutsch: 'Sport', chinese: '運動', gender: 'der', plural: '', Pl: '', countable: false, lesson: 'lesson 2'},
    { type: 'noun', deutsch: 'Problem', chinese: '問題 難題 課題', gender: 'das', plural: 'Probleme', Pl: '-e', countable: true, lesson: 'lesson 2'},
    { type: 'noun', deutsch: 'Haus', chinese: '房屋 透天', gender: 'das', plural: 'Häuser', Pl: '-:er', countable: true, lesson: 'lesson 2'},
    { type: 'noun', deutsch: 'Garten', chinese: '花園', gender: 'der', plural: 'Gärten', Pl: '-:', countable: true, lesson: 'lesson 2'},
    { type: 'noun', deutsch: 'Zahl', chinese: '數字', gender: 'die', plural: 'Zahlen', Pl: '-en', countable: true, lesson: 'lesson 2'},
    { type: 'noun', deutsch: 'Postleitzahl', chinese: '郵遞區號', gender: 'die', plural: 'Postleitzahlen', Pl: '-en', countable: true, lesson: 'lesson 2'},
    { type: 'noun', deutsch: 'Briefmarke', chinese: '郵票', gender: 'die', plural: 'Briefmarken', Pl: '-n', countable: true, lesson: 'lesson 2'},
    { type: 'noun', deutsch: 'Partner', chinese: '同伴 伴侶', gender: 'der', plural: 'Partner', Pl: '-', countable: true, lesson: 'lesson 2'},
    { type: 'noun', deutsch: 'Straße', chinese: '街', gender: 'die', plural: 'Straßen', Pl: '-n', countable: true, lesson: 'lesson 2'},
    { type: 'noun', deutsch: 'Hausnummer', chinese: '門牌號碼', gender: 'die', plural: 'Hausnummern', Pl: '-n', countable: true, lesson: 'lesson 2'},
    { type: 'noun', deutsch: 'Handynummer', chinese: '手機號碼', gender: 'die', plural: 'Handynummern', Pl: '-n', countable: true, lesson: 'lesson 2'},
    { type: 'noun', deutsch: 'Telefonnummer', chinese: '電話號碼', gender: 'die', plural: 'Telefonnummern', Pl: '-n', countable: true, lesson: 'lesson 2'},
    { type: 'noun', deutsch: 'Absender', chinese: '寄件人', gender: 'der', plural: 'Absender', Pl: '-', countable: true, lesson: 'lesson 2'},
    { type: 'noun', deutsch: 'Empfänger', chinese: '收件人', gender: 'der', plural: 'Empfänger', Pl: '-', countable: true, lesson: 'lesson 2'},
    { type: 'noun', deutsch: 'Postkarte', chinese: '明信片', gender: 'die', plural: 'Postkarten', Pl: '-n', countable: true, lesson: 'lesson 2'},
    { type: 'noun', deutsch: 'Postkasten', chinese: '郵筒 信箱', gender: 'der', plural: 'Postkästen', Pl: '-:', countable: true, lesson: 'lesson 2'},
    { type: 'noun', deutsch: 'Computer', chinese: '電腦', gender: 'der', plural: 'Computer', Pl: '-', countable: true, lesson: 'lesson 2'},
    { type: 'noun', deutsch: 'Lehrer', chinese: '老師', gender: 'der', plural: 'Lehrer', Pl: '-', countable: true, lesson: 'lesson 2'},
    { type: 'noun', deutsch: 'Lehrerin', chinese: '女老師', gender: 'die', plural: 'Lehrerinnen', Pl: '-nen', countable: true, lesson: 'lesson 2'},
    { type: 'noun', deutsch: 'Herr', chinese: '先生 主人', gender: 'der', plural: 'Herren', Pl: '-en', countable: true, lesson: 'lesson 2'},
    { type: 'noun', deutsch: 'Frau', chinese: '小姐 女士 女人', gender: 'die', plural: 'Frauen', Pl: '-en', countable: true, lesson: 'lesson 2'},
    { type: 'noun', deutsch: 'Mann', chinese: '男人', gender: 'der', plural: 'Männer', Pl: '-:er', countable: true, lesson: 'lesson 2'},
    { type: 'noun', deutsch: 'Morgen', chinese: '早晨', gender: 'der', plural: 'Morgen', Pl: '-', countable: true, lesson: 'lesson 2'},
    { type: 'noun', deutsch: 'Fußball', chinese: '足球（運動）', gender: 'der', plural: '', Pl: '', countable: false, lesson: 'lesson 2'},
    { type: 'noun', deutsch: 'Verein', chinese: '社團 聯盟 協會', gender: 'der', plural: 'Vereine', Pl: '-e', countable: true, lesson: 'lesson 2'},
    { type: 'noun', deutsch: 'Profi', chinese: '職業運動員', gender: 'der', plural: 'Profis', Pl: '-s', countable: true, lesson: 'lesson 2'},
    { type: 'noun', deutsch: 'Mannschaft', chinese: '球隊 組織', gender: 'die', plural: 'Mannschaften', Pl: '-en', countable: true, lesson: 'lesson 2'},
    { type: 'noun', deutsch: 'Profimannschaft', chinese: '職業球隊', gender: 'die', plural: 'Profimannschaften', Pl: '-en', countable: true, lesson: 'lesson 2'},
    { type: 'noun', deutsch: 'Torwart', chinese: '守門員', gender: 'der', plural: 'Torwarte', Pl: '-e', countable: true, lesson: 'lesson 2'},
    { type: 'noun', deutsch: 'Dorf', chinese: '鄉村', gender: 'das', plural: 'Dörfer', Pl: '-:er', countable: true, lesson: 'lesson 2'},
    { type: 'noun', deutsch: 'Spieler', chinese: '球員 參賽者', gender: 'der', plural: 'Spieler', Pl: '-', countable: true, lesson: 'lesson 2'},
    { type: 'noun', deutsch: 'Trainer', chinese: '教練', gender: 'der', plural: 'Trainer', Pl: '-', countable: true, lesson: 'lesson 2'},
    { type: 'noun', deutsch: 'Training', chinese: '訓練', gender: 'das', plural: '', Pl: '', countable: false, lesson: 'lesson 2'},
    { type: 'noun', deutsch: 'Nationalspieler', chinese: '國手', gender: 'der', plural: 'Nationalspieler', Pl: '-', countable: true, lesson: 'lesson 2'},
    { type: 'noun', deutsch: 'Heimat', chinese: '祖國 故鄉', gender: 'der', plural: 'Heimaten', Pl: '-en', countable: true, lesson: 'lesson 2'},

    
    
// { type: 'noun', deutsch: '', chinese: '', gender: '', plural: '', Pl: '', countable: true, lesson: 'lesson '},
// 特殊字符 Ä ä Ö ö Ü ü ß
];
